[package]
name = "wast-preprocessor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
wast = "39.0.0"
cc = "1.0.73"

[dev-dependencies]
wasm-tools = "1.0.1"